### ISSUE TITLE
Combine Toggl entries with same description

### ISSUE THREAD

**Issue by hans2103** [peterjaap/TogglMoneybirdIntegration#18]
Would be nice if TogglMoneybirdIntergration could combine Toggl entries with the same description. (I'm using Toggl in both mail, Github and Bitbucket. Pressing **Start timer** and **Stop timer**)

**Comment by peterjaap** [comment]
See https://github.com/peterjaap/TogglMoneybirdIntegration/commit/5fa7b9adcfb84c449d3c990d126ae28b12153374
