### ISSUE TITLE
Feature Request: add date to Moneybird description

### ISSUE THREAD

**Issue by eschoonheim** [peterjaap/TogglMoneybirdIntegration#23]
Hi,

is it possible to send the starttime and stoptime for the entry to Moneybird as the period?

Now every entry has the same period of the timeframe I am billing for.

<img width="401" alt="screen shot 2018-11-07 at 10 59 25" src="https://user-images.githubusercontent.com/7381125/48124302-410d1a80-e27c-11e8-841e-1069df8dd281.png">

**Comment by peterjaap** [comment]
@eschoonheim unfortunately Moneybird doesn't support times in those fields.

Bytheway I'm not actively working on this anymore since we moved on from both Toggl and Moneybird.

**Comment by eschoonheim** [comment]
OK thanks
